spring:
  application.name: logmonitor
  datasource:
    url: jdbc:h2:mem:logmonitor
    driverClassName: org.h2.Driver

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show.details: true

logging.file.path: C:\distributed-system-concepts\logs
